# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0af83828deb7c24f31cd3ea3ec46aed091d9f5a25a5a66870b241af7213794b5e02f2ad548109077e49d44702feea0a53b0a3cc705e218d9b8c56349ea3d7863

test:
  secret_key_base: 4dc2117ce4e4c3cbf244fd40581b56f7afe9438b2e15652e1f7a4c9835a7e68c76760f44eb6f7c923ff2a4a836997f9a0484502bea203e086446932abed746a4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
